Aj ddos protection 5.0.0
Juniper-SE/Apstra_IBA_Probes pull request #20
Opened 2024-10-29 12:34 UTC by iamjarvs

@mehdi-juniper all aspects updated, ready for your review

2024-10-30 11:12 UTC, mehdi-juniper requested changes
Have done a first pass. I like the way the collector has been authored and described in the Readme, really nice work.
I have some questions/comments on the way probe has been designed as well as the resulted Dashboard, I left some comments as I think some adjustment might be needed there.
I created a variant of the probe/dashboard [here](https://10.28.218.3/#/blueprints/evpn-vex-virtual/analytics/dashboards/f5a7650b-db47-4d2f-ad3b-8c68664617c1) and I also uploaded it to the AI lab, hoping that the IXIA traffic gen would create some violations too. In terms of analytics, I think the probe should focus on either the `state` column (possible values are `OK` or `viol`) and/or the **Violation_Count** column, rather than on the dropped packet ones. It is possible that a siwtch has a policer where the threshold is more than one packet drop.

2024-10-31 11:55 UTC, iamjarvs commented on release_5.0.0/DDoS_Protection_Protocols/Content/Final_Dashboard_Control_Plane_DDoS_Protection.json
> +        "label": "DDoS Protection Violation Changes - 1Min",
Using your version, done

2024-10-31 11:55 UTC, iamjarvs commented on release_5.0.0/DDoS_Protection_Protocols/Content/Final_Dashboard_Control_Plane_DDoS_Protection.json
> +        "label": "DDoS Protection Violation Changes History - 24Hrs",
Using your version, done

2024-10-31 11:55 UTC, iamjarvs commented on release_5.0.0/DDoS_Protection_Protocols/Content/Final_Dashboard_Control_Plane_DDoS_Protection.json
> +          "name": "Extensible Service Collector",
Using your version, done

2024-10-31 11:55 UTC, iamjarvs commented on release_5.0.0/DDoS_Protection_Protocols/README.md
> +To implement the anomaly raising logic for reboot in last **1h** / **1 day** / **1 week** without duplicating the anomalies (i.e having a device which rebooted 45mn ago to appear in both 1h and 1day)
Layer 8 moment - removed

2024-10-31 12:00 UTC, iamjarvs commented
@mehdi-juniper  please re-review, changes made

2024-10-31 12:01 UTC, iamjarvs commented on release_5.0.0/DDoS_Protection_Protocols/Content/Final_Dashboard_Control_Plane_DDoS_Protection.json
> +        "label": "DDoS Protection Violation Changes History - 24Hrs",
Using your version, done

2024-10-31 12:01 UTC, iamjarvs commented on release_5.0.0/DDoS_Protection_Protocols/Content/Final_Dashboard_Control_Plane_DDoS_Protection.json
> +      "label": "ddos-protection-protocols",
Using your version, done

2024-11-04 10:40 UTC, mehdi-juniper approved these changes
Looks Great!, found few minor type-o/spelling errors, other than that it's great. Approving.

2024-11-04 10:40 UTC, mehdi-juniper commented on release_5.0.0/DDoS_Protection_Protocols/README.md
> +- Collect device's DDoS policer violation statistics for all protocols and raise an anomaly whenevr a protocol has an increment of the violation count.
type o `whenever`

2024-11-04 10:40 UTC, mehdi-juniper commented on release_5.0.0/DDoS_Protection_Protocols/README.md
> +- Keep track of these anomalies in MetricDB so user can back in time and look for any protocol DDoS violation.
so user can `go` back ..

2024-11-04 10:40 UTC, mehdi-juniper commented on release_5.0.0/DDoS_Protection_Protocols/README.md
> +Pay attention to the expression used in the `Value` and the logic to convert the text string provided by the `policer-violation-count` field into an integer value. The  `policer-violation-count` fiel
type o: should `only`

2024-11-05 17:33 UTC, iamjarvs commented
Fixed, merged, branch removed

2024-11-05 17:33 UTC, merged